name: Action CI

on:
  workflow_call:

jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install PHP
        uses: shivammathur/setup-php@1a18b2267f80291a81ca1d33e7c851fe09e7dfc4 # v2.22.0
        with:
          php-version: 8.1
          extensions: yaml
          tools: composer:v2

      - name: Run CI
        run: |
          if [[ -f composer.json ]]; then
            composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --no-plugins
          fi
          if [[ -f vendor/bin/phpunit ]]; then
            vendor/bin/phpunit
          else
            echo "No phpunit tests found"
          fi

  gauge-release:
    name: Gauge release
    runs-on: ubuntu-latest
    needs: ci
    outputs:
      do_release: ${{ steps.gauge-release.outputs.do_release }}
      next_tag: ${{ steps.gauge-release.outputs.next_tag }}
    steps:
      - name: Gauge release
        id: gauge-release
        uses: emteknetnz/gha-gauge-release@main

  patch-release:
    name: Patch release
    runs-on: ubuntu-latest
    needs: gauge-release
    if: ${{ needs.gauge-release.outputs.do_release == '1' }}
    steps:
      - name: Patch release
        uses: silverstripe/gha-tag-release@v1
        with:
          tag: ${{ needs.gauge-release.outputs.next_tag }}
          delete_existing: false
          release: true
          release_auto_notes: true
